
WHITESPACE = _{ " " }

number = @{ ASCII_DIGIT+ }
three_numbers = _{ number ~ ( " " ~ number ){2} }
values = { ( LINE_SEPARATOR ~ three_numbers )+ ~ LINE_SEPARATOR* }

seeds = { "seeds:" ~ number+ ~ LINE_SEPARATOR+ }
seed_to_soil = { "seed-to-soil map:" ~ values }
soil_to_fertilizer = { "soil-to-fertilizer map:" ~ values }
fertilizer_to_water = { "fertilizer-to-water map:" ~ values }
water_to_light = { "water-to-light map:" ~ values }
light_to_temperature = { "light-to-temperature map:" ~ values }
temperature_to_humidity = { "temperature-to-humidity map:" ~ values }
humidity_to_location = { "humidity-to-location map:" ~ values }

main = {
    seeds ~ 
    seed_to_soil ~
    soil_to_fertilizer ~
    fertilizer_to_water ~ 
    water_to_light ~
    light_to_temperature ~
    temperature_to_humidity ~
    humidity_to_location
}

// seeds: 79 14 55 13

// seed-to-soil map:
// 50 98 2
// 52 50 48

// soil-to-fertilizer map:
// 0 15 37
// 37 52 2
// 39 0 15

// fertilizer-to-water map:
// 49 53 8
// 0 11 42
// 42 0 7
// 57 7 4

// water-to-light map:
// 88 18 7
// 18 25 70

// light-to-temperature map:
// 45 77 23
// 81 45 19
// 68 64 13

// temperature-to-humidity map:
// 0 69 1
// 1 0 69

// humidity-to-location map:
// 60 56 37
// 56 93 4
