
day01:
	clang-18 -Wall -Werror --debug aoc2023/day01.c -o a.out && ./a.out
day02:
	clang-18 -Wall -Werror --debug aoc2023/day02.c -o a.out && ./a.out
day03:
	clang-18 -Wall -Werror --debug aoc2023/day03.c -o a.out && ./a.out


# gcc -g3 -Wall -Wextra -Wconversion -Wdouble-promotion -Wno-unused-parameter -Wno-unused-function -Wno-sign-conversion -fsanitize=undefined,address,null,leak -std=c2x aoc2023/day03.c
# gcc -Wall -Wextra -Wconversion -Wdouble-promotion -Wno-unused-parameter -Wno-unused-function -Wno-sign-conversion aoc2023/day03.c 