[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"
include = ["../data", ]

[dependencies]
pest = { version = "2.7.7", features = ["pretty-print"] }
pest_derive = { version = "2.7.7", features = [] }